veterinary-clinic/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :animal_passports
  resources :animals
  resources :appointments
  resources :doctors
  resources :owners
  resources :treatments

end

veterinary-clinic/app/models/doctor.rb
class Doctor < ActiveRecord::Base
	def shown_graduation_date
	  date_of_graduation.to_date
	end

	def shown_birth_date
	  date_of_birth.to_date 
	end
end

veterinary-clinic/app/models/owner.rb
class Owner < ActiveRecord::Base
end

veterinary-clinic/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

veterinary-clinic/app/controllers/doctors_controller.rb
class DoctorsController  < ApplicationController
	before_action :set_doctor, only: [:show, :update, :destroy, :edit]
	def new
	  @doctor = Doctor.new
	end

	def create
	  @doctor = Doctor.new(doctor_params)

	  if @doctor.save
	    redirect_to doctors_path
	  else
	    render 'new'
	  end
	end

	def show
	end

	def index
	  @doctors = Doctor.all
	end

	def edit
	end

	def update

	  if @doctor.update(doctor_params)
	    redirect_to @doctor
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @doctor.destroy

	  redirect_to doctors_path
	end

	private
	  def doctor_params
	    params.require(:doctor).permit(
	    	:fname,
	    	:lname,
	    	:email,
	    	:date_of_birth,
	    	:date_of_graduation
	    	)
	  end
	  def set_doctor
	  	 @doctor = Doctor.find(params[:id])
	  end
end

veterinary-clinic/app/controllers/owners_controller.rb
class OwnersController  < ApplicationController
	before_action :set_owner, only: [:show, :update, :destroy, :edit]
	def new
	  @owner = Owner.new
	end

	def create
	  @owner = Owner.new(owner_params)

	  if @owner.save
	    redirect_to owners_path
	  else
	    render 'new'
	  end
	end

	def show
	end

	def index
	  @owners = Owner.all
	end

	def edit
	end

	def update

	  if @owner.update(owner_params)
	    redirect_to @owner
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @owner.destroy

	  redirect_to owners_path
	end

	private
	  def owner_params
	    params.require(:owner).permit(
	    	:fname,
	    	:lname,
	    	:owner_of_an_animal
	    	)
	  end
	  def set_owner
	  	 @owner = Owner.find(params[:id])
	  end
end

veterinary-clinic/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

veterinary-clinic/app/helpers/application_helper.rb
module ApplicationHelper
end

veterinary-clinic/app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <% if @doctor.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited
      this doctor from being saved:</h2>
    <ul>
    <% @doctor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
    <p>
      <%= f.label "Име" %>
      <%= f.text_field :fname %>
    </p>

    <p>
      <%= f.label "Фамилия" %>
      <%= f.text_field :lname %>
    </p>

    <p>
      <%= f.label "Имейл" %>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label  "Рожденна дата" %>
      <%= f.date_select(:date_of_birth, start_year: 1935) %>
    </p>

    <p>
      <%= f.label  "Година на дипломиране" %>
      <%= f.date_select(:date_of_graduation, start_year: 1935) %>
    </p>

    <p>
      <%= f.submit value: "Запази"%>  
    </p>
<% end %>

veterinary-clinic/app/views/doctors/edit.html.erb
<div id="wrap">
	<h1> Редактирай доктор </h1>

	<%= render 'form' %>
	 
	<%= link_to 'Назад', doctors_path %>
</div>

veterinary-clinic/app/views/doctors/index.html.erb
<div id="wrap">
  <%= render 'welcome/menu' %>
  <h1>Доктори</h1>
   
  <table class = "index-table">
    <tr class = "line-one">
      <th>Име</th>
      <th>Фамилия</th>
      <th>Имейл</th>
      <th>Рожденна дата </th>
      <th>Година на дипломиране </th>
    </tr>
   
    <% @doctors.each do |doctor| %>
      <tr class = "line-two">
        <td><%= doctor.fname %></td>
        <td><%= doctor.lname %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.shown_birth_date %></td>
        <td><%= doctor.shown_graduation_date %></td>
        <td><%= link_to 'Преглед', doctor_path(doctor) %></td>
        <td><%= link_to 'Редактирай', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Изтрий', doctor_path(doctor), method: :delete %></td>
      </tr>
    <% end %>
  </table>
   <%= link_to 'Назад', root_path %>
   | <%= link_to 'Нов доктор', new_doctor_path %> 
</div>

veterinary-clinic/app/views/doctors/new.html.erb
<div id="wrap">
	<h1> Нов доктор </h1>

	<%= render 'form' %>
</div>

veterinary-clinic/app/views/doctors/show.html.erb
<div id="wrap">
	<p class = "show-train-station">
	  Име: <%= @doctor.fname %>
	</p>

	<p class = "show-doctor-station">
	  Фамилия: <%= @doctor.lname %>
	</p>

	<p class = "show-doctor-station">
	  Имейл: <%= @doctor.email %>
	</p>

	<p class = "show-doctor-station">
	  Рожденна дата: <%= @doctor.shown_birth_date %>
	</p>

	<p class = "show-train-station">
	  Година на дипломиране: <%= @doctor.shown_graduation_date %>
	</p>

	<%= link_to 'Назад', doctors_path %>
	| <%= link_to 'Редактирай', edit_doctor_path(@doctor) %>
</div>

veterinary-clinic/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VeterinaryClinic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

veterinary-clinic/app/views/owners/_form.html.erb
<%= form_for @owner do |f| %>
  <% if @owner.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@owner.errors.count, "error") %> prohibited
      this owner from being saved:</h2>
    <ul>
    <% @owner.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
    <p>
      <%= f.label "Име" %>
      <%= f.text_field :fname %>
    </p>

    <p>
      <%= f.label "Фамилия" %>
      <%= f.text_field :lname %>
    </p>

    <p>
      <%= f.label "Собственик на" %>
      <%= f.text_field :owner_of_an_animal %>
    </p>

    <p>
      <%= f.submit value: "Запази"%>  
    </p>
<% end %>

veterinary-clinic/app/views/owners/edit.html.erb
<div id="wrap">
	<h1> Редактирай собтвеник </h1>

	<%= render 'form' %>
	 
	<%= link_to 'Назад', owners_path %>
</div>

veterinary-clinic/app/views/owners/index.html.erb
<div id="wrap">
  <%= render 'welcome/menu' %>
  <h1>Собственици</h1>
   
  <table class = "index-table">
    <tr class = "line-one">
      <th>Име</th>
      <th>Фамилия</th>
      <th>Собственик на </th>
    </tr>
   
    <% @owners.each do |owner| %>
      <tr class = "line-two">
        <td><%= owner.fname %></td>
        <td><%= owner.lname %></td>
        <td><%= owner.owner_of_an_animal %></td>
        <td><%= link_to 'Преглед', owner_path(owner) %></td>
        <td><%= link_to 'Редактирай', edit_owner_path(owner) %></td>
        <td><%= link_to 'Изтрий', owner_path(owner), method: :delete %></td>
      </tr>
    <% end %>
  </table>
   <%= link_to 'Назад', root_path %>
   | <%= link_to 'Нов собственик', new_owner_path %> 
</div>

veterinary-clinic/app/views/owners/new.html.erb
<div id="wrap">
	<h1> Нов собственик </h1>

	<%= render 'form' %>

	<%= link_to 'Назад', owners_path %>
</div>

veterinary-clinic/app/views/owners/show.html.erb
<div id="wrap">
	<p class = "show-train-station">
	  Име: <%= @owner.fname %>
	</p>

	<p class = "show-owner-station">
	  Фамилия: <%= @owner.lname %>
	</p>

	<p class = "show-doctor-station">
	  Собственик на: <%= @owner.owner_of_an_animal %>
	</p>

	<%= link_to 'Назад', owners_path %>
	| <%= link_to 'Редактирай', edit_owner_path(@owner) %>
</div>

veterinary-clinic/app/views/welcome/_menu.html.erb
<table class = "index-page">
  <tr>
      <td><%= link_to 'Доктори', doctors_path %></td>
      <td><%= link_to 'Собственици', owners_path %></td>
      <td><%= link_to 'Животни', animal_passports_path %></td>
      <td><%= link_to 'Прегледи', appointments_path %></td>
      <td><%= link_to 'Лечения', treatments_path %></td>
      <td><%= link_to 'Паспорти', animal_passports_path %></td>
  </tr>
</table>

veterinary-clinic/app/views/welcome/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300&subset=latin,cyrillic-ext,cyrillic' rel='stylesheet' type='text/css'>    
</head>
<body>
     <%= render 'menu' %>
</body>
</html>